name: NFL Spread Predictor Pipeline

on:
  # schedule:
  #   - cron: '0 0 * * 2'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1

      - name: Install dependencies with Poetry
        run: poetry install

      - name: Download data
        run: poetry run python ./nfl_analytics/main.py --download

      # Necessary for train step
      # https://github.com/actions/runner-images/discussions/7188#discussioncomment-6750749
      # https://stackoverflow.com/questions/71590851/r8-is-causing-gradle-daemon-to-vanish-on-github-hosted-action-runner/76921482#76921482
      - name: Increase swapfile
        run: |
          df -h
          sudo swapoff -a
          sudo fallocate -l 12G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      # Seperated from Download data to make debugging easier
      - name: Train Model
        run: poetry run python ./nfl_analytics/main.py --train

      # TODO: tag name? release name?
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./nfl_analytics/assets/*
          tag_name: spread-predictor
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload model, scaler, and running average dataframe
        id: upload_assets
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: ./nfl_analytics/assets/*

      - name: Attach assets to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ needs.upload_assets.outputs.artifact_paths }}
          asset_name: assets
          asset_content_type: application/zip
